name: Frontend build and deploy

on:
    # workflow_dispatch:
    # pull_request:
    #     types:
    #         - opened
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Checks out the code from the repository.
            - name: Get code
              uses: actions/checkout@v3
            # Installs Node.js.
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                  # The `node-version` variable specifies that any minor or patch version of Node.js is acceptable.
                  node-version: 18.x
            # Installs the dependencies ci(locked dep.)
            - name: Install dependencies
              run: npm ci
            # Builds the app
            - name: Build
              run: npm run build
            # Uploads the build directory as an artifact
            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: ng-git-workflow-dist-files
                  path: dist
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Get build artifact
              uses: actions/download-artifact@v3
              with:
                  name: ng-git-workflow-dist-files
            - name: Output contents of artifact
              run: |
                  cd ng-git-workflow-dist-files/dist
                  ls
            - name: Deploy
              run: echo "Deploying...!"
