name: Matrix Demo
on:
    push:
        branches:
            - master

jobs:
    build:
        strategy:
            matrix:
                node-version: [14.x, 16.x, 18.x]
                operating-system: [ubuntu-latest, windows-latest]

        runs-on: ${{ matrix.operating-system }}
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              run: npm ci
            - name: Build project
              run: npm run build
